name: Angular CI
on: 
  push:
    branches: [main, development]
  pull_request:
    branches: [main, development]
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - run: npm ci
      - run: npm run test:ci
  build-app:
    runs-on: ubuntu-latest
    needs: unit-tests
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - run: npm ci
      - run: npm run build:ci
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: app-build
          path: |
            dist/pomovu/browser